repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=40000, --enforce-all]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        stages: [pre-push]
        additional_dependencies:
          - types-aiofiles
          - types-cachetools
          - types-python-dateutil
          - types-python-slugify
          - types-pytz
          - types-PyYAML
          - types-redis
          - types-requests
          - types-six
          - types-tabulate
          - types-toml
        args:
          - --ignore-missing-imports
          - --no-namespace-packages
          - --enable-incomplete-feature=Unpack
          - --python-version=3.12
